app:
  security:
    secret-key: BankRestAppSecretKey1234
    algorithm: AES
    card-expiration-years: 5
    max-transfer-amount: 500000

jwt:
  secret: gh23hj45f3g2h45f234hfg5235hj2ya23jhh
  expiresIn: 3600000
  issuer: bank-rest-app

spring:
  application:
    name: bank-rest-application
  datasource:
    url: jdbc:postgresql://db:5432/bank_rest_db
    username: bank-rest
    password: bank-rest-password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
