app:
  security:
    secret-key: ${APP_SECRET_KEY:BankRestAppSecretKey1234}
    algorithm: AES
    card-expiration-years: 5
    max-transfer-amount: 500000

jwt:
  secret: ${JWT_SECRET:defaultSecret}
  expiresIn: 3600000
  issuer: bank-rest-app

spring:
  application:
    name: bank-rest-application
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_rest_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html